### ISSUE TITLE
Async call after Google authentication

### ISSUE THREAD

**Issue by KoldBrewEd** [awslabs/aws-cognito-apigw-angular-auth#1]
Sometimes the async call to get the temporary credentials from Cognito after the Google authentication does not return the credentials and it requires to authenticate a second time. Working on a better callback strategy.

**Comment by markdernie** [comment]
Thanks for putting this together it was very useful. I also had the problem with the google authentication but it wasn't intermittent. I think the issue is that the google authentication is called from a different component (google-signin) from the testgoogle function (app). This means that the googlecallback is called in google-signin not app so the loggedInCreds doesn't get set in app. I added this.awsService.getgoogleData(this); to the testGoogle function to force the local googleCallback to be called, and it seems to work now.  Thanks again for putting the example together it was an really big help in my understanding of this area.

**Comment by KoldBrewEd** [comment]
Thanks for that! Would you mind creating a pull request with your fix? It'd be very helpful, I'll get it merged straight away

**Comment by KoldBrewEd** [comment]
Merged
